### ISSUE TITLE
Package takeover

### ISSUE THREAD

**Issue by sigrlami** [kseo/language-dart#2]
Hi, I tried to reach you by email but without success. 
I want take over package maintainership to add more features that match current state of Dart ecosystem. I can it to my fork but would prefer to have ability upload to hackage. 

Let me know if that's possible to arrange.

**Comment by sigrlami** [comment]
@blamario hi, any hints on how to connect?

**Comment by blamario** [comment]
Sorry, I have no special access either. At this point I suppose you can follow the [Hackage takeover](https://wiki.haskell.org/Taking_over_a_package) policy.

**Comment by sigrlami** [comment]
@blamario thanks! takeover initiated.

**Comment by blamario** [comment]
BTW, I'd be happy to help as a co-maintainer.

**Comment by sigrlami** [comment]
Nice! I'll contact Hackage admins to make us maintainers next week and will send you notification. On Jul 28, 2019 19:34, Mario <notifications@github.com> wrote:BTW, I'd be happy to help as a co-maintainer.

**Comment by blamario** [comment]
> Nice! I'll contact Hackage admins to make us maintainers next week and will send you notification

Er... not so fast. The takeover policy I linked above says

> 1. Try to contact the maintainer. Give him/her reasonable time to respond.
> 2. State your intention to take over the package in a public forum (we recommend the haskell-cafe and/or libraries list). CC the maintainer.
> 3. Wait a while.
> ...
> 1. From time of announcement of intention to takeover to actual takeover, there will be a 2-6 week period where the admins give the maintainer a chance to respond, with the exact time in any case up to the discretion of the admins.

**Comment by sigrlami** [comment]
@blamario ah, I missed 2-6 weeks period. Anyway, I'll let you know how it progress.

**Comment by werediver** [comment]
Excuse me for an off-topic question, but...

@blamario You did a great job in your fork fixing/updating/extending this library. As this repo is not maintained anymore, your fork would be a good successor. I wonder, which Dart version it targets? (we have an [ECMA standard for Dart 2](https://dart.dev/guides/language/spec) [perhaps, 2.2])

A better place for this question would be in the fork's issues, but they are disabled 🤷‍♂️

**Comment by blamario** [comment]
I have enabled the issues in the fork.

As for the Dart version, it's at an indeterminate version between the root repo and 2.2. That's because I tried to follow the current standrd at the time, but I didn't want to modify the AST too far.

**Comment by sigrlami** [comment]
@blamario @werediver I have a closed fork with many more corrections that also contains code from @blamario. I believe best course of action here gain maintainership rights and start publishing. My aim is upstream as I use this package for my flutter bindings I plan to release this autumn.

**Comment by werediver** [comment]
@sigrlami Do you plan to make your fork public before the autumn release? This way you may get some collaborators and start gaining visibility.

I'm also curious about what's meant by the Flutter bindings. You mean the Google Flutter, right? (I'm using it at work)

**Comment by sigrlami** [comment]
@werediver yes, I'll release mine soon and yes it's for Google Flutter, I have experimental transpiler that generates Dart code from Haskell

**Comment by kseo** [comment]
@sigrlami I am sorry for being late to respond to your messages. Would you tell me your Hacakage account? I will add you to the list of maintainers.

**Comment by sigrlami** [comment]
@kseo Hi, thank you for response! My nickname also `sigrlami`. If you like me to continue work within this repository also please add me and @blamario as contributors.

**Comment by kseo** [comment]
@sigrlami Done!

**Comment by sigrlami** [comment]
@kseo thank you! access gained
